Add migrating to 8.0 guide
smartdevicelink/sdl_core_guides pull request #133
Opened 2021-10-05 19:58 UTC by JackLivio

Add information to highlight important integration updates. This guide includes updates to the accepted environments, configuration options, and HMI API updates integrators will need to take note of.

2021-10-06 14:15 UTC, iCollin commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +This parameter was added to the smartDeviceLink.ini configuration to help compensate for timing issues that could occur during `BasicCommunication.OnResetTimeout`. This value is added to the DefaultT
I think this section could use some more information, and be a bit clearer, as it isn't necessarily related to resetting the timeout.

Background: `DefaultTimeoutCompensation` is a value Core adds to each timeout when waiting for a message response. This value is to compensate for the time a message spends "in the wire". For example, when Mobile requests an alert with a timeout of 5000ms, Core processes this message before the HMI, so if it set a timer for just 5000ms, it would expire and mobile would be sent GENERIC_ERROR before the HMI's TIMEOUT response is processed by Core. In prior releases, Core hardcoded adding additional time to some requests that may receive a TIMEOUT response. This new INI option `DefaultTimeoutCompensation` replaces the hardcoded timeout extensions with a configurable value that applies to all requests.

```suggestion
This parameter was added to the smartDeviceLink.ini configuration to compensate for transfer and processing time of requests. This value is added to the DefaultTimeout parameter when calculating the RPC request timeout. Previously, specific requests such as Alert were hardcoded to extend their default timeout, now timeout compensation is configurable and applied to all requests.
```

2021-10-06 14:40 UTC, iCollin commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +# Migrating SDL Core 7.1 to 8.0
Another section should be added for 0205, maybe something like this:

## HMI Updates

### Avoid Custom button subscription in case HMI incompatibility

SDL Core 8.0.0 no longer automatically subscribes to `CUSTOM_BUTTON`. If an HMI supports soft buttons, it must include an entry for `CUSTOM_BUTTON` in its' button capabilities in order for mobile to receive OnButtonPress and OnButtonEvent notifications.

2021-10-06 15:22 UTC, jacobkeeler commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +
Should probably include a section for the behavior changes for the phone call event here:

## OnEventChanged (PHONE_CALL)

The behavior of the `PHONE_CALL` event was changed to only affect the `audioStreamingState` of an app. Rather than automatically deactivating the active app, SDL Core will now only change the `audioStreamingState` of all apps to `NOT_AUDIBLE` when `BC.OnEventChanged(PHONE_CALL, active=true)` is sent, leaving each app's `hmiLevel` unchanged. This allows the HMI to start a phone call in the background without leaving the app screen, if desired.

The HMI can still control the `hmiLevel` of the app during a phone call event by sending `BC.OnAppDeactivated(appID)` and `BC.OnAppActivated(appID)` where appropriate.

2021-10-06 21:34 UTC, jacobkeeler approved these changes

2021-10-07 14:05 UTC, ShobhitAd requested changes

2021-10-07 14:05 UTC, ShobhitAd commented on config.json
> +                    "name": "Migrating SDL Core 7.1 to 8.0"
We might want to also add a link to this guide in the overview page https://smartdevicelink.com/en/guides/core/overview/#migrating-to-newer-sdl-versions

2021-10-07 14:05 UTC, ShobhitAd commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +SDL Core 8.0.0 dropped support for libssl1.0. Developers should install libssl-dev instead of libssl1.0-dev
```suggestion
SDL Core 8.0.0 dropped support for libssl1.0. Developers should install `libssl-dev` instead of `libssl1.0-dev`
```

2021-10-07 14:05 UTC, ShobhitAd commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +## Buttons.SubscribeButton
```suggestion
### Buttons.SubscribeButton
```

2021-10-07 14:05 UTC, ShobhitAd commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +## Buttons.UnsubscribeButton
```suggestion
### Buttons.UnsubscribeButton
```

2021-10-07 14:05 UTC, ShobhitAd commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +## Restructuring OnResetTimeout
```suggestion
### Restructuring OnResetTimeout 
```

2021-10-07 14:07 UTC, ShobhitAd commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +The parameter `resetPeriod` allows the HMI to specify how long Core should delay the application request’s timeout.
```suggestion
The parameters in the notification have also changed:
- The parameter `requestID` is used instead of appID to identify which specific request should have its timeout extended.
- The parameter `methodName` should include the interface name and the rpc. For example: `”TTS.Speak”`.
- The parameter `resetPeriod` allows the HMI to specify how long Core should delay the application request’s timeout.
```

2021-10-07 14:53 UTC, theresalech requested changes
@JackLivio please let me know if you have any questions about my feedback. Thanks!

2021-10-07 14:53 UTC, theresalech commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +The default logger is still using LOG4CXX but the option is now available to use Boost for the logger. When porting SDL Core to different linux environments, the LOG4CXX logger was known to cause dep
```suggestion
The default logger is still using LOG4CXX but the option is now available to use Boost for the logger. When porting SDL Core to different Linux environments, the LOG4CXX logger was known to cause dependency issues. Boost is offered as an alternative logger in hopes of making porting SDL Core to different environments easier.
```

2021-10-07 14:53 UTC, theresalech commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +This parameter was added to the smartDeviceLink.ini configuration to compensate for transfer and processing time of requests. This value is added to the DefaultTimeout parameter when calculating the
```suggestion
This parameter was added to the smartDeviceLink.ini configuration to compensate for transfer and processing time of requests. This value is added to the `DefaultTimeout` parameter when calculating the RPC request timeout. Previously, specific requests such as Alert were hardcoded to extend their default timeout, now timeout compensation is configurable and applied to all requests.
```

2021-10-07 14:53 UTC, theresalech commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +SDL Core 8.0.0 no longer automatically subscribes to `CUSTOM_BUTTON`. If an HMI supports soft buttons, it must include an entry for `CUSTOM_BUTTON` in its' button capabilities in order for mobile to
```suggestion
SDL Core 8.0.0 no longer automatically subscribes to `CUSTOM_BUTTON`. If an HMI supports soft buttons, it must include an entry for `CUSTOM_BUTTON` in its button capabilities in order for mobile to receive `OnButtonPress` and `OnButtonEvent` notifications.
```

2021-10-07 14:53 UTC, theresalech commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +### SSL versions
```suggestion
### SSL Versions
```

2021-10-07 14:53 UTC, theresalech commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +### Avoid Custom button subscription in case HMI incompatibility
```suggestion
### Avoid Custom Button Subscription in Case HMI Incompatibility
```

2021-10-07 14:53 UTC, theresalech commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +			<description>The ID of the application requesting this button usubscription. </description>
```suggestion
			<description>The ID of the application requesting this button subscription. </description>
```

2021-10-07 14:53 UTC, theresalech commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +`Buttons.OnButtonSubscription` notification was replaced by `Buttons.SubscribeButton` Request and Response.
```suggestion
`Buttons.OnButtonSubscription` notification was replaced by `Buttons.SubscribeButton` request and response.
```

2021-10-07 14:53 UTC, theresalech commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +`UI.OnResetTimeout` and `TTS.OnResetTimeout` were removed in place of using a broader rpc, `BasicCommunication.OnResetTimeout`.
```suggestion
`UI.OnResetTimeout` and `TTS.OnResetTimeout` were removed in place of using a broader RPC, `BasicCommunication.OnResetTimeout`.
```

2021-10-07 14:53 UTC, theresalech commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +The parameter `methodName` should include the interface name and the rpc. For example: `”TTS.Speak”`.
```suggestion
The parameter `methodName` should include the interface name and the RPC. For example: `”TTS.Speak”`.
```

2021-10-07 14:53 UTC, theresalech commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +SDL Core 8.0.0 dropped support for libssl1.0. Developers should install libssl-dev instead of libssl1.0-dev
```suggestion
SDL Core 8.0.0 dropped support for libssl1.0. Developers should install libssl-dev instead of libssl1.0-dev.
```

2021-10-07 14:53 UTC, theresalech commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +`Buttons.UnsubscribeButton` request and response were added to allow SDL Core to request the HMI unsubscribes an application from a specific button.
```suggestion
`Buttons.UnsubscribeButton` request and response were added to allow SDL Core to request that the HMI unsubscribes an application from a specific button.
```

2021-10-07 14:53 UTC, theresalech commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +The parameter `requestID` is used instead of appID to identify which specific request should have its timeout extended.
```suggestion
The parameter `requestID` is used instead of `appID` to identify which specific request should have its timeout extended.
```

2021-10-07 14:53 UTC, theresalech commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +The parameter `methodName` should include the interface name and the rpc. For example: `”TTS.Speak”`.
Additional question: should this be `TTS.Speak` or are the double quotes intentional?

2021-10-07 16:09 UTC, Jack-Byrne commented on config.json
> +                    "name": "Migrating SDL Core 7.1 to 8.0"
Done

2021-10-07 16:10 UTC, Jack-Byrne commented on docs/Migrating to Newer SDL Versions/Migrating SDL Core 7.1 to 8.0/index.md
> +The default logger is still using LOG4CXX but the option is now available to use Boost for the logger. When porting SDL Core to different linux environments, the LOG4CXX logger was known to cause dep
Updated to "hopes of making"

2021-10-07 18:12 UTC, theresalech approved these changes

2021-10-07 19:04 UTC, ShobhitAd approved these changes

2021-10-07 19:07 UTC, merged